### ISSUE TITLE
获取个人信息时出现错误

### ISSUE THREAD

**Issue by minimax4233** [Tishacy/ZJU-nCov-Hitcarder#12]
⏰ 已启动定时程序，每天 00:20 为您打卡
Press Ctrl+C to exit

[Time] 2020-04-16 00:20:00
🚌 打卡任务启动
✔ 已新建打卡实例
✔ 已登录到浙大统一身份认证平台
⠼ 正在获取个人信息...Job "main (trigger: cron[hour='0', minute='20'], next run at: 2020-04-17 00:20:00 HKT)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "daka.py", line 99, in main
    dk.get_info()
  File "daka.py", line 49, in get_info
    old_info = json.loads(re.findall(r'oldInfo: ({[^}]+})', html)[0])
IndexError: list index out of range

在old_info后面加了一行print(re.findall(r'oldInfo: ({[^}]+})', html)[0])也没显示啥
在前面加就报错这样:
✔ 已新建打卡实例
✔ 已登录到浙大统一身份认证平台
⠼ 正在获取个人信息...Job "main (trigger: cron[hour='0', minute='24'], next run at: 2020-04-17 00:24:00 HKT)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "daka.py", line 99, in main
    dk.get_info()
  File "daka.py", line 49, in get_info
    print(re.findall(r'oldInfo: ({[^}]+})', html)[0])
IndexError: list index out of range

PS,daka.py上添加了
new_info['address'] = '' 
new_info['area'] = '中国 香港'
new_info['province'] = '香港'
new_info['city'] = '香港'

**Comment by Tishacy** [comment]
其他人也遇到过这个正则匹配不上的bug，但是比较奇怪我的没有遇到过这个问题，而且我也只能登陆我的账号，所以没法复现bug...

如果方便的话，你可以把 [每日上报](https://healthreport.zju.edu.cn/ncov/wap/default) （登录后）这个页面的html文件下载下来发我邮箱：tishacy@gmail.com，我看看那个正则匹配到底哪里出了问题，谢谢支持~

**Comment by Tishacy** [comment]
> ⏰ 已启动定时程序，每天 00:20 为您打卡
> Press Ctrl+C to exit
> 
> [Time] 2020-04-16 00:20:00
> 🚌 打卡任务启动
> ✔ 已新建打卡实例
> ✔ 已登录到浙大统一身份认证平台
> ⠼ 正在获取个人信息...Job "main (trigger: cron[hour='0', minute='20'], next run at: 2020-04-17 00:20:00 HKT)" raised an exception
> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/dist-packages/apscheduler/executors/base.py", line 125, in run_job
> retval = job.func(*job.args, **job.kwargs)
> File "daka.py", line 99, in main
> dk.get_info()
> File "daka.py", line 49, in get_info
> old_info = json.loads(re.findall(r'oldInfo: ({[^}]+})', html)[0])
> IndexError: list index out of range
> 
> 在old_info后面加了一行print(re.findall(r'oldInfo: ({[^}]+})', html)[0])也没显示啥
> 在前面加就报错这样:
> ✔ 已新建打卡实例
> ✔ 已登录到浙大统一身份认证平台
> ⠼ 正在获取个人信息...Job "main (trigger: cron[hour='0', minute='24'], next run at: 2020-04-17 00:24:00 HKT)" raised an exception
> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/dist-packages/apscheduler/executors/base.py", line 125, in run_job
> retval = job.func(*job.args, **job.kwargs)
> File "daka.py", line 99, in main
> dk.get_info()
> File "daka.py", line 49, in get_info
> print(re.findall(r'oldInfo: ({[^}]+})', html)[0])
> IndexError: list index out of range
> 
> PS,daka.py上添加了
> new_info['address'] = ''
> new_info['area'] = '中国 香港'
> new_info['province'] = '香港'
> new_info['city'] = '香港'

其他人也遇到过这个正则匹配不上的bug，但是比较奇怪我的没有遇到过这个问题，而且我也只能登陆我的账号，所以没法复现bug...

如果方便的话，你可以把 [每日上报](https://healthreport.zju.edu.cn/ncov/wap/default) （登录后）这个页面的html文件下载下来发我邮箱：tishacy@gmail.com，我看看那个正则匹配到底哪里出了问题，谢谢支持~
