### ISSUE TITLE
1月1号开始脚本好像失灵啦

### ISSUE THREAD

**Issue by jessychen1016** [Tishacy/ZJU-nCov-Hitcarder#17]
球球大佬改改

**Comment by jessychen1016** [comment]
报错信息：Relative info not found in html with regex

**Comment by Tishacy** [comment]
表单应该是没有改动的，可能是因为网络等原因脚本漏打了一天，导致找不到上一天缓存的数据。
pull 下最近新的代码，然后手动打卡一天，后面脚本应该就可以找到今天打卡缓存的数据了。

**Comment by jessychen1016** [comment]
好的好的,谢谢哈
