### ISSUE TITLE
无法获取缓存信息

### ISSUE THREAD

**Issue by JouleYuan** [Tishacy/ZJU-nCov-Hitcarder#22]
5.3号又恢复打卡了，但是不知道为什么现在缓存信息加载不了了，old_info根本获取不了。我用chrome看了一下，现在oldInfo那一项直接就是空的，只剩下了def那里的缓存信息，但是不全，希望解决一下

更新一下：
今天试了下可以了，不知道为什么这个是要求你前一天打了卡才会有缓存信息，很奇怪

**Comment by SDaydreamer** [comment]
虽然我不会操作网页，但是我把我该填的信息全写死在程序里了，（因为我今天打过了只能看到‘今日已填报’，明天试试），这样就解决了ac01
