### ISSUE TITLE
Mac系统无法运行

### ISSUE THREAD

**Issue by Zhuyuhan99** [Tishacy/ZJU-nCov-Hitcarder#3]
运行后只输出了第一行Press Ctrl+C to exit
然后就卡住了，不知道怎么回事😲

**Comment by Tishacy** [comment]
> 运行后只输出了第一行Press Ctrl+C to exit
> 然后就卡住了，不知道怎么回事😲

那就是正常定时任务正常运行啦
你可以先把定的时间放在最近的一个时间（比如下一分钟）看下到时间是否可以正常打卡

**Comment by Zhuyuhan99** [comment]
> > 运行后只输出了第一行Press Ctrl+C to exit
> > 然后就卡住了，不知道怎么回事😲
> 
> 那就是正常定时任务正常运行啦
> 你可以先把定的时间放在最近的一个时间（比如下一分钟）看下到时间是否可以正常打卡

可以了 感谢！！
