### ISSUE TITLE
这个脚本失效了, 98有老哥说是添加了两个字段

### ISSUE THREAD

**Issue by cwy1119** [Tishacy/ZJU-nCov-Hitcarder#32]
具体参见 https://www.cc98.org/topic/5131469

**Comment by hliangzhao** [comment]
查看打卡页面的源码，发现第600行多了两个键值对
因此在新信息new_info上填入即可。具体地，在103行之后加上如下两行：
```Python
new_info['23676ad88cb0953fa0e229b32e886f62'] = '1628132969'
new_info['f6f259ba6791b79b64e0559fbe41050d'] = '9a3e997026e31e3174cc3c5521f08dd3'
```

**Comment by hliangzhao** [comment]
> 查看打卡页面的源码，发现第600行多了两个键值对
> 因此在新信息new_info上填入即可。具体地，在103行之后加上如下两行：
> 
> ```python
> new_info['23676ad88cb0953fa0e229b32e886f62'] = '1628132969'
> new_info['f6f259ba6791b79b64e0559fbe41050d'] = '9a3e997026e31e3174cc3c5521f08dd3'
> ```

测试发现，这里键值对的“值”是动态生成在html上的，但是作者似乎并未对值进行检查。以上的代码在别的同学的机器上测试有效。

**Comment by Tishacy** [comment]
https://github.com/Tishacy/BatchHitcarder 的 v1.0.2 版本已更新这两个参数，可以先使用此版本继续打卡，这个脚本我也会尽快更新。
