### ISSUE TITLE
login without phantomjs

### ISSUE THREAD

**Issue by conv1d** [Tishacy/ZJU-nCov-Hitcarder#4]
```python
import requests
import re

username = ''
password = ''

sess = requests.Session()

def _rsa_encrypt(password_str, e_str, M_str):
    password_bytes = bytes(password_str, 'ascii') # I guess no other characters in password
    password_int = int.from_bytes(password_bytes, 'big') # big endian bytes->int
    e_int = int(e_str, 16) # equal to 0x10001
    M_int = int(M_str, 16) # Modulus number
    result_int = pow(password_int, e_int, M_int) # pow is a built-in function in python
    return hex(result_int)[2:].rjust(128, '0') # int->hex str

url  = 'https://zjuam.zju.edu.cn/cas/login?service=https://healthreport.zju.edu.cn/a_zju/api/sso/index?redirect=https://healthreport.zju.edu.cn/ncov/wap/default/index&from=wap'

res = sess.get(url)
execution = re.search('name="execution" value="(.*?)"', res.text).group(1)
res = sess.get(url='https://zjuam.zju.edu.cn/cas/v2/getPubKey').json()
n, e = res['modulus'], res['exponent']
encrypt_password = _rsa_encrypt(password, e, n)

data = {
    'username': username,
    'password': encrypt_password
    'execution': execution,
    '_eventId': 'submit'
}
res = sess.post(url=url, data=data)
print(res.text)
```

**Comment by Tishacy** [comment]
> ```python
> import requests
> import re
> 
> username = ''
> password = ''
> 
> sess = requests.Session()
> 
> def _rsa_encrypt(password_str, e_str, M_str):
>     password_bytes = bytes(password_str, 'ascii') # I guess no other characters in password
>     password_int = int.from_bytes(password_bytes, 'big') # big endian bytes->int
>     e_int = int(e_str, 16) # equal to 0x10001
>     M_int = int(M_str, 16) # Modulus number
>     result_int = pow(password_int, e_int, M_int) # pow is a built-in function in python
>     return hex(result_int)[2:].rjust(128, '0') # int->hex str
> 
> url  = 'https://zjuam.zju.edu.cn/cas/login?service=https://healthreport.zju.edu.cn/a_zju/api/sso/index?redirect=https://healthreport.zju.edu.cn/ncov/wap/default/index&from=wap'
> 
> res = sess.get(url)
> execution = re.search('name="execution" value="(.*?)"', res.text).group(1)
> res = sess.get(url='https://zjuam.zju.edu.cn/cas/v2/getPubKey').json()
> n, e = res['modulus'], res['exponent']
> encrypt_password = _rsa_encrypt(password, e, n)
> 
> data = {
>     'username': username,
>     'password': encrypt_password
>     'execution': execution,
>     '_eventId': 'submit'
> }
> res = sess.post(url=url, data=data)
> print(res.text)
> ```

大佬棒 马上改

**Comment by Tishacy** [comment]
Thanks buddy~

tt <notifications@github.com> 于2020年2月12日周三 下午3:20写道：

**Comment by conv1d** [comment]
It's OK~
