### ISSUE TITLE
Please remove big files before.

### ISSUE THREAD

**Issue by QSCTech-Sange** [Tishacy/ZJU-nCov-Hitcarder#5]
Files concerning `PhantomJS` that committed before make it difficult to clone this repo.

Though the latest version has deleted these files, they remain in the `Git` history.

Please consider
```
git filter-branch -f --prune-empty --index-filter 'git rm -rf --cached --ignore-unmatch {your-file-name}' --tag-name-filter cat -- --all
```
and then
```
git push origin --force --all
```
Good Luck!

**Comment by Tishacy** [comment]
> Files concerning `PhantomJS` that committed before make it difficult to clone this repo.
> 
> Though the latest version has deleted these files, they remain in the `Git` history.
> 
> Please consider
> 
> ```
> git filter-branch -f --prune-empty --index-filter 'git rm -rf --cached --ignore-unmatch {your-file-name}' --tag-name-filter cat -- --all
> ```
> 
> and then
> 
> ```
> git push origin --force --all
> ```
> 
> Good Luck!

Thanks buddy~

**Comment by saysin** [comment]
如何避开vpn获取真实的地理地址，现在显示的是我代理的香港地址。
