### ISSUE TITLE
如何避开vpn获取真实的地理地址，现在显示的是我代理的香港地址。

### ISSUE THREAD

**Issue by saysin** [Tishacy/ZJU-nCov-Hitcarder#8]
如何避开vpn获取真实的地理地址，现在显示的是我代理的香港地址。

**Comment by Tishacy** [comment]
> 如何避开vpn获取真实的地理地址，现在显示的是我代理的香港地址。

- 程序执行的时候，并不是使用实时获取的地理位置，而是使用上一次打卡时所用的地址。所以如果第一次打卡时使用的是期望的地理位置，那程序每天打卡就会一直使用该位置，不依赖服务器实际地理地址或VPN代理地址。
- 如果是想指定自己的地理位置，可以按如下方法修改`daka.py`文件:
    - 找到`get_info`函数（第43行），并在`# form change`注释（第58行）上方添加如下代码：

        ```python
        new_info['address'] = '你的详细地位置'   # 如: 'xx省xx市xx区xx街道xx小区'
        new_info['area'] = 'xx省 xx市 xx区'     # 如: '浙江省 杭州市 西湖区'  记得中间用空格隔开, 省市区/县名称可以参考 打卡页面->基本信息->家庭所在地 中对应的省市区/县名
        new_info['province'] = new_info['area'].split(' ')[0]   # 省名
        new_info['city'] = new_info['area'].split(' ')[1]       # 市名
        ```
    - 保存重新执行即可

**Comment by FuNian788** [comment]
请问北京应该如何提交呢 北京市+北京市还是？
