### ISSUE TITLE
在国外使用的问题

### ISSUE THREAD

**Issue by Frost-Lee** [Tishacy/ZJU-nCov-Hitcarder#9]
因为人在国外，”所在地点（请打开手机定位功能...）“一栏无法获取地理位置，因此需要在”所在地点“选择“国外”。但此值不会被自动存储，需要每次打卡时勾选。使用自动打卡时日志如下：

```
[Time] 2020-02-15 06:12:00
🚌 打卡任务启动
✔ 已新建打卡实例例...
✔ 已登录到浙大统一身份认证平台.
✔ 316010xxxx 李xx同学, 你好~
🦄  今日内是否在以下地区停留格式错误
```

请问这个有办法修复么🤔️

**Comment by Tishacy** [comment]
这个跟 issue #8 的问题差不多，就是需要手动改一下代码把地址设为国外。
- 首先确保一下童鞋你的打卡文件`daka.py`为最新的
- 然后，找到`get_info`函数（第43行），并在`# form change`注释（第58行）上方添加如下代码：

    ```python
    new_info['address'] = ''   # 空串
    new_info['area'] = '国外'
    new_info['province'] = '国外'
    new_info['city'] = '国外'
    ```
- 保存重新执行即可

还有提醒一下时差问题~ 程序里的定时时间对应的是主机（或服务器）所在时区，所以要是学院有规定必须北京时间6-12点内打卡（我们学院就是这样= =）记得换算成你所在的时区。

**Comment by Frost-Lee** [comment]
> 这个跟 issue #8 的问题差不多，就是需要手动改一下代码把地址设为国外。
> 
> * 首先确保一下童鞋你的打卡文件`daka.py`为最新的
> * 然后，找到`get_info`函数（第43行），并在`# form change`注释（第58行）上方添加如下代码：
>   ```python
>   new_info['address'] = ''   # 空串
>   new_info['area'] = '国外'
>   new_info['province'] = '国外'
>   new_info['city'] = '国外'
>   ```
> * 保存重新执行即可
> 
> 还有提醒一下时差问题~ 程序里的定时时间对应的是主机（或服务器）所在时区，所以要是学院有规定必须北京时间6-12点内打卡（我们学院就是这样= =）记得换算成你所在的时区。
> 
> 另，膜MIT大佬~

可用了！感谢🙏
